name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: current folder
        run: 'pwd'
        
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: get content of folder
        run: ls ${{github.workspace}}
        
      - name: print a message
        run: echo 'run gcc'
      
      - name: compile
        run: gcc cat.c -o cat
             
